image: docker:stable

services:
    - docker:dind

job:
    tags:
        - docker
    before_script:
        - docker info
        - apk update
        - apk add bash
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - bash build_all.bash
        - bash push_all.bash
